# TownyFlight by LlmDl.
Version: 1.6.7
# Prefix to messages seen in game.
pluginPrefix: '&8[&3TownyFlight&8] '
####################
# Language Strings #
####################

language:
  # Message shown when flight activated.
  flightOnMsg: Uçuş aktif hale getirildi.
  # Message shown when flight de-activated.
  flightOffMsg: Uçuş devre dışı bırakıldı.
  # Message shown when player lacks a town. 
  noTownMsg: Uçabilmek için bir kasabaya dahil olman gerek.
  # Message shown when flight cannot be turned on.
  notInTownMsg: Uçabilmek için kasaba sınırları içerisinde olman gerek.
  # Message shown when a player has flight taken away.
  flightDeactivatedMsg: Kasaba sınırlarından ayrıldığın için uçuş modun devredışı bırakıldı.
  # Message shown when a player has flight taken away because of PVP.
  flightDeactivatedPVPMsg: Savaşa girdiğin için uçuş modun devredışı bırakıldı.
  # Message shown when a player has flight taken away by console.
  flightDeactivatedConsoleMsg: Uçuş ayrıcalıkları kaldırıldı.
  # Message shown when a player lacks a permission node.
  noPermission: Bu komutu kullanmak için yeterli yetkiye sahip değilsin!
  # Message shown when war is active and flight is disallowed.
  notDuringWar: Savaş sırasında uçuş modunu aktifleştiremezsin.
  # Message telling a player to return to an allowed flight area.
  returnToAllowedArea: İzin verilen bir uçuş bölgesine dönmek için %s saniyeniz var.
#################       
#    Options    #
#################

options:
  # If set to true, players entering their town will have flight auto-enabled.
  # When set to true, the plugin will use slightly more resources due to the EnterTown listener.
  auto_Enable_Flight: 'false'
  # If set to true, players entering their town will have flight auto-enabled without being notified in chat.
  auto_Enable_Silent: 'false'
  # If set to false, players can still fly in their town while war is active.
  disable_During_Wartime: 'true'
  # If set to false, TownyFlight will not prevent combat of flying people.
  disable_Combat_Prevention: 'false'
  # If set to false, the language.noPermission message will not display the permission node.
  show_Permission_After_No_Permission_Message: 'true'
  # Number of seconds after leaving an allowed flight area before flight is taken away.
  # Set to 0 to take flight away immediately.
  flight_Disable_Timer: '3'
